//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYCWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_WORKSTATISTICS
    {
        public string as_psn { get; set; }
        public string as_workmonth { get; set; }
        public Nullable<int> as_totaltime { get; set; }
        public Nullable<int> as_basetime { get; set; }
        public Nullable<int> as_timegap { get; set; }
        public Nullable<System.DateTime> as_updatetime { get; set; }
        public string as_updateuser { get; set; }
    }
}
