//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HYCWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HYCEntities : DbContext
    {
        public HYCEntities()
            : base("name=HYCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AS_MEMBER> AS_MEMBER { get; set; }
        public virtual DbSet<AS_WORKTIME> AS_WORKTIME { get; set; }
        public virtual DbSet<AS_SALARY> AS_SALARY { get; set; }
        public virtual DbSet<AS_WORKSTATISTICS> AS_WORKSTATISTICS { get; set; }
    }
}
